INSERT INTO students_data
VALUES 
   ("Mustafa Hussien" , 1, "Data Science and Ai"),
     ("Abdelrahman Waleed" ,2 , "Data Science and Ai"),
    ("Youssef Mamdouh" , 3, "Data Science and Ai"),
     ("Ahmed Magdy" , 4, "Data Science and Ai"),
     ("Nada Mohamed" , 5, "Data Science and Ai"),
    ("Yahia Mohamed", 6, "Data Science and Ai"),
     ("Mahmoud Hassan" ,7 , "Data Science and Ai"),
     ("Ganna Tarek" , 8, "Data Science and Ai"),
     ("Marium Hossam" , 9, "Data Science and Ai"),
     ("Wael Ayman" ,10, "Data Science and Ai"),
     ("Thomas Nabil" ,11 , "Data Science and Ai"),
     ("Menna Mohamed" , 12 , "Data Science and Ai"),
     ("Habiba Ahmed" , 13 , "Data Science and Ai"),
     ("Mohamed Ahmed" , 14 , "Data Science and Ai"),
     ("Mohamed Saleh" , 15 , "Data Science and Ai"),
     ("Adham Mahomud" , 16 , "Data Science and Ai"),
     ("Ezz Eldien" , 17 , "Data Science and Ai"),
     ("Ahmed Abdelrahman" , 18 , "Data Science and Ai"),
     ("Youssef Ashraf" , 19 , "Data Science and Ai"),
     ("Nabil Adel" , 20 , "Data Science and Ai"),
     ("Marim Mohamed" , 21 , "Data Science and Ai"),
     ("Youssef Sherif" , 22, "Data Science and Ai"),
     ("Mlisia Mkram" , 23 , "Data Science and Ai"),
     ("Omar Hazem" , 24 , "Data Science and Ai"),
     ("Mohamed Hamed" , 25 , "Data Science and Ai"),
     ("Youssef Yasser", 26 , "Data Science and Ai"),
     ("Moahme Essam",27 , "Data Science and Ai"),
     ("Ammar Hussien", 28, "Data Science and Ai"),
     ("Omar Awad",29 , "Data Science and Ai"),
     ("Kareem Adel", 30 , "Data Science and Ai"),
     ("Hazem Mohamed", 31 , "Data Science and Ai"),
     ("Omar Mohamed", 32 , "Data Science and Ai"),
     ("Mohab Ahmed", 33 , "Data Science and Ai"),
     ("Marwan Osama", 34 , "Data Science and Ai"),
     ("Abdullah Mohamed", 35 , "Data Science and Ai"),
     ("Moahemd Ashraf", 36 , "Data Science and Ai"),
     ("Anas Moahmed", 37 , "Data Science and Ai"),
     ("Mohaned Gaber", 38 , "Data Science and Ai"),
     ("Abdelrhman Mohamed", 39 , "Data Science and Ai"),
     ("Mustafa Mohamed", 40 , "Data Science and Ai"),
     ("Mustafa Mahmoud", 41 , "Data Science and Ai"),
     ("Nour Ahmed",42 , "Data Science and Ai"),
     ("Marim Hani", 43 , "Data Science and Ai"),
     ("Marim Gerges", 44 , "Data Science and Ai"),
     ("Shahd Akram", 45 , "Data Science and Ai"),
     ("Menna Yasser", 46 , "Data Science and Ai"),
     ("Marim Mohamed", 47 , "Data Science and Ai"),
     ("Mamdouh Abdelkader", 48 , "Data Science and Ai"),
     ("Youssef Ahmed", 49 , "Data Science and Ai"),
     ("Abdulah Mahomud", 50 , "Data Science and Ai");
     
SELECT * FROM students_data